# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [(b'activity', '0001_initial'), (b'activity', '0002_auto_20190207_1054'), (b'activity', '0003_auto_20190207_1108'), (b'activity', '0004_auto_20190207_1308'), (b'activity', '0005_auto_20190207_1315'), (b'activity', '0006_auto_20190207_1718'), (b'activity', '0007_auto_20190207_1742'), (b'activity', '0008_auto_20190207_1747'), (b'activity', '0009_auto_20190208_0659'), (b'activity', '0010_auto_20190208_0716'), (b'activity', '0011_auto_20190208_0717'), (b'activity', '0012_auto_20190208_0724')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=256)),
                ('object', models.CharField(max_length=256, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('modification_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('modification_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_id', to='activity.User'),
        ),
        migrations.AddField(
            model_name='activity',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_id', to='activity.User'),
        ),
        migrations.CreateModel(
            name='FriendShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.IntegerField(unique=True)),
                ('friend_ids', models.TextField(default=['13'])),
                ('creation_time', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('modification_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'friend_status',
            },
        ),
        migrations.AlterModelTable(
            name='activity',
            table='activity_feed',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='modification_time',
        ),
        migrations.AddField(
            model_name='activity',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='modification_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='target',
        ),
        migrations.AddField(
            model_name='activity',
            name='actor_id',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='target_id',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set([('actor_id', 'verb', 'object', 'target_id')]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='target_id',
            field=models.IntegerField(null=True),
        ),
    ]
