# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_squashed_0012_auto_20190208_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='friend_ids',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set([]),
        ),
        migrations.AlterModelTable(
            name='activity',
            table=None,
        ),
        migrations.AlterModelTable(
            name='friendship',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
