# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20190207_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='target',
        ),
        migrations.AddField(
            model_name='friendship',
            name='actor_id',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendship',
            name='target_ids',
            field=models.TextField(default=['13']),
            preserve_default=False,
        ),
    ]
