# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20190207_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='actor_id',
            field=models.IntegerField(unique=True),
        ),
    ]
