# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20190207_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='modification_time',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='modification_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modification_time',
        ),
    ]
