# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20190207_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='modification_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='friendship',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendship',
            name='modification_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='modification_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
