# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20190207_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='target_ids',
            new_name='friend_ids',
        ),
    ]
