# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_auto_20190207_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='target',
        ),
        migrations.AddField(
            model_name='activity',
            name='actor_id',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='target_id',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
    ]
