# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20190208_0716'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set([('actor_id', 'verb', 'object', 'target_id')]),
        ),
    ]
